# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/baloneo/ClionProject/network-ball-gtk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/baloneo/ClionProject/network-ball-gtk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/baloneo/ClionProject/network-ball-gtk/CMakeFiles /home/baloneo/ClionProject/network-ball-gtk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/baloneo/ClionProject/network-ball-gtk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named network-ball-gtk

# Build rule for target.
network-ball-gtk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 network-ball-gtk
.PHONY : network-ball-gtk

# fast build rule for target.
network-ball-gtk/fast:
	$(MAKE) -f CMakeFiles/network-ball-gtk.dir/build.make CMakeFiles/network-ball-gtk.dir/build
.PHONY : network-ball-gtk/fast

src/application.o: src/application.c.o

.PHONY : src/application.o

# target to build an object file
src/application.c.o:
	$(MAKE) -f CMakeFiles/network-ball-gtk.dir/build.make CMakeFiles/network-ball-gtk.dir/src/application.c.o
.PHONY : src/application.c.o

src/application.i: src/application.c.i

.PHONY : src/application.i

# target to preprocess a source file
src/application.c.i:
	$(MAKE) -f CMakeFiles/network-ball-gtk.dir/build.make CMakeFiles/network-ball-gtk.dir/src/application.c.i
.PHONY : src/application.c.i

src/application.s: src/application.c.s

.PHONY : src/application.s

# target to generate assembly for a file
src/application.c.s:
	$(MAKE) -f CMakeFiles/network-ball-gtk.dir/build.make CMakeFiles/network-ball-gtk.dir/src/application.c.s
.PHONY : src/application.c.s

src/utils.o: src/utils.c.o

.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) -f CMakeFiles/network-ball-gtk.dir/build.make CMakeFiles/network-ball-gtk.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) -f CMakeFiles/network-ball-gtk.dir/build.make CMakeFiles/network-ball-gtk.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) -f CMakeFiles/network-ball-gtk.dir/build.make CMakeFiles/network-ball-gtk.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... network-ball-gtk"
	@echo "... edit_cache"
	@echo "... src/application.o"
	@echo "... src/application.i"
	@echo "... src/application.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

